# Configuration for CV
person:
  first_name: Adam
  last_name: Pollack
  title: Assistant Professor
  university: University of Iowa
  department: School of Earth, Environment, and Sustainability
  department_link: https://https://sees.uiowa.edu/
  email: adam-pollack@uiowa.edu
  web: https://abpoll.github.io/
  github: abpoll
  googlescholar: mnigw6AAAAAJ
  orcid: 0000-0001-6642-0591
  address:
    line1: 316 Jessup Hall
    line2: 5 West Jefferson Street
    postcode: Iowa City, IA 52242
    country: USA

paths:
  bib_path: bibliography
  yaml_path: data

publications:
  - title: Papers
    file: my-papers.bib
  - title: Conference Papers
    file: conferences.bib

sections:
  - title: Research Interests
    file: interests.yml
  - title: Appointments
    file: appointments.yml
  - title: Education
    file: education.yml
  - title: Invited Talks
    file: talks.yml
  - title: Advising
    file: advising.yml
  - title: Teaching
    file: teaching.yml
  - title: Awards
    file: awards.yml
  - title: Peer Review
    file: peerreview.yml
  - title: Service
    file: service.yml
  - title: Grants and Contracts
    file: grants.yml
  - title: Media Coverage
    file: media.yml
